Лабораторная работа №1
sergey-berezin/401_mozgovyx pull request #1
Opened 2023-09-23 15:15 UTC by vasily-mozgovykh

Сделал лабораторную работу в форкнутом репозитории. Асинхронное взаимодействие с общей памятью реализовал через SemaphoreSlim. Nuget-пакет выложил на nuget.org, исходный код в репозитории.

2023-09-24 18:43 UTC, sergey-berezin requested changes

2023-09-24 18:43 UTC, sergey-berezin commented on Lab 1/YoloPackage/YoloPackage.cs
> +        public static CancellationTokenSource cts = new CancellationTokenSource();
CancellationTokenSource обычно создают пользователь компонент. Сами компоненты используют CancellationToken.

2023-09-24 18:43 UTC, sergey-berezin commented on Lab 1/YoloPackage/YoloPackage.cs
> +            await data.CopyToAsync(fileStream);
Где обрабатываются ошибки загрузки?

2023-09-24 18:43 UTC, sergey-berezin commented on Lab 1/YoloPackage/YoloPackage.cs
> +        public static async Task<YoloSegmentation> ProcessImage(Image<Rgb24> image)
Метод по сути синхронный, так как не порождает новых задач. 

Код t1 = ProcessImage(...) вернёт задачу только когда она уже завершилась.

2023-09-27 22:49 UTC, vasily-mozgovykh commented on Lab 1/YoloPackage/YoloPackage.cs
> +        public static CancellationTokenSource cts = new CancellationTokenSource();
Исправил, поменял логику создания задач

2023-09-27 22:50 UTC, vasily-mozgovykh commented on Lab 1/YoloPackage/YoloPackage.cs
> +            await data.CopyToAsync(fileStream);
В методе SetUpModel ошибка загрузки обрабатывается через создание сессии. В версии без токенов GetStreamAsync могла бросить исключение, с токенами не может

2023-09-27 22:50 UTC, vasily-mozgovykh commented on Lab 1/YoloPackage/YoloPackage.cs
> +        public static async Task<YoloSegmentation> ProcessImage(Image<Rgb24> image)
Поменял последовательность действий на последовательность задач

2023-09-29 08:05 UTC, sergey-berezin requested changes

2023-09-29 08:05 UTC, sergey-berezin commented on Lab 1/ConsoleApp/Program.cs
> +        private static CancellationTokenSource cts = new CancellationTokenSource();
Активируйте токен по Ctrl+C.

2023-10-05 06:44 UTC, merged